services:
  web:
    networks:
      - frontend
  ndbmgmt:
    image: container-registry.oracle.com/mysql/community-cluster:${EXAMSYS_DOCKER_CLUSTERVERSION}
    command: ndb_mgmd
    networks:
      cluster:
        ipv4_address: 192.168.0.2
    volumes:
      - ./conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
  ndbnode1:
    image: container-registry.oracle.com/mysql/community-cluster:${EXAMSYS_DOCKER_CLUSTERVERSION}
    command: ndbd
    networks:
      cluster:
        ipv4_address: 192.168.0.3
    depends_on:
      - ndbmgmt
  ndbnode2:
    image: container-registry.oracle.com/mysql/community-cluster:${EXAMSYS_DOCKER_CLUSTERVERSION}
    command: ndbd
    networks:
      cluster:
        ipv4_address: 192.168.0.4
    depends_on:
      - ndbmgmt
  db:
    image: container-registry.oracle.com/mysql/community-cluster:${EXAMSYS_DOCKER_CLUSTERVERSION}
    networks:
      frontend:
      cluster:
        ipv4_address: 192.168.0.10
    environment:
      MYSQL_ROOT_PASSWORD: ${EXAMSYS_DOCKER_MYSQLROOT}
      MYSQL_ROOT_HOST: "%"
      TZ: ${EXAMSYS_DOCKER_MYSQLTZ}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p${EXAMSYS_DOCKER_MYSQLROOT}"]
      interval: 10s
      timeout: 5s
      retries: 4
    depends_on:
      - ndbmgmt
      - ndbnode1
      - ndbnode2
networks:
  frontend:
    driver: bridge
  cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
